### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by b2renger** [josephtaylor/sketch-mapper#4]
Hi,

I'm testing nthis library which is awesome btw. I get a OutOfMemoryError quite often.

I'm on ubuntu 15.04 using processing 2.2.1. Here is the full log :

java.lang.RuntimeException: java.lang.OutOfMemoryError
    at com.jogamp.common.util.awt.AWTEDTExecutor.invoke(AWTEDTExecutor.java:58)
    at jogamp.opengl.awt.AWTThreadingPlugin.invokeOnOpenGLThread(AWTThreadingPlugin.java:103)
    at jogamp.opengl.ThreadingImpl.invokeOnOpenGLThread(ThreadingImpl.java:206)
    at javax.media.opengl.Threading.invokeOnOpenGLThread(Threading.java:172)
    at javax.media.opengl.Threading.invoke(Threading.java:191)
    at javax.media.opengl.awt.GLCanvas.display(GLCanvas.java:541)
    at processing.opengl.PJOGL.requestDraw(PJOGL.java:688)
    at processing.opengl.PGraphicsOpenGL.requestDraw(PGraphicsOpenGL.java:1651)
    at processing.core.PApplet.run(PApplet.java:2256)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.OutOfMemoryError
    at sun.misc.Unsafe.allocateMemory(Native Method)
    at java.nio.DirectByteBuffer.<init>(Unknown Source)
    at java.nio.ByteBuffer.allocateDirect(Unknown Source)
    at processing.opengl.PGL.allocateDirectIntBuffer(PGL.java:1933)
    at processing.opengl.PGL.updateIntBuffer(PGL.java:1960)
    at processing.opengl.Texture.updatePixelBuffer(Texture.java:831)
    at processing.opengl.Texture.set(Texture.java:348)
    at processing.opengl.Texture.set(Texture.java:311)
    at processing.opengl.PGraphicsOpenGL.initCache(PGraphicsOpenGL.java:6163)
    at processing.opengl.PGraphicsOpenGL.getTexture(PGraphicsOpenGL.java:6115)
    at processing.opengl.PGraphicsOpenGL$TexCache.getTexture(PGraphicsOpenGL.java:6918)
    at processing.opengl.PGraphicsOpenGL.flushPolys(PGraphicsOpenGL.java:2464)
    at processing.opengl.PGraphicsOpenGL.flush(PGraphicsOpenGL.java:2415)
    at processing.opengl.PGraphicsOpenGL.endDraw(PGraphicsOpenGL.java:1712)
    at processing.core.PApplet.handleDraw(PApplet.java:2406)
    at processing.opengl.PJOGL$PGLListener.display(PJOGL.java:862)
    at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:665)
    at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:649)
    at javax.media.opengl.awt.GLCanvas$10.run(GLCanvas.java:1289)
    at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1119)
    at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:994)
    at javax.media.opengl.awt.GLCanvas$11.run(GLCanvas.java:1300)
    at java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$200(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)

When I tested on windows I didn't recall seeing those kind of errors. I will try several graphics drivers.

**Comment by josephtaylor** [comment]
Have you tried increasing the memory in processing? If you go to File->Preferences there's an option to "Increase maximum available memory" ... I would set that to something larger than 256MB like 512MB or 1024MB ... assuming your system has enough resources to support that.

**Comment by b2renger** [comment]
Yes I did I'm using 1024, I will try more :)

edit : I tried to run the example sketch with 2048, I get the same error. Couldn't run with 4096.

**Comment by b2renger** [comment]
I switched to latest proprietary nvidia drivers (346.59), I don't seem to have errors anymore.

I guess you can consider this closed, and see if it reopens.

**Comment by josephtaylor** [comment]
ah, glad to hear it !
