### ISSUE TITLE
Processing 3 Incompatibility

### ISSUE THREAD

**Issue by josephtaylor** [josephtaylor/sketch-mapper#7]
Running the example sketch yields the following trace:

```
java.lang.RuntimeException: java.lang.IllegalAccessError: tried to access field processing.core.PApplet.sketchPath from class jto.processing.sketch.mapper.BezierOptionsMenu
    at processing.opengl.PSurfaceJOGL$2.run(PSurfaceJOGL.java:446)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalAccessError: tried to access field processing.core.PApplet.sketchPath from class jto.processing.sketch.mapper.BezierOptionsMenu
    at jto.processing.sketch.mapper.BezierOptionsMenu.compileSourceList(BezierOptionsMenu.java:117)
    at jto.processing.sketch.mapper.BezierOptionsMenu.<init>(BezierOptionsMenu.java:110)
    at jto.processing.sketch.mapper.SketchMapper.<init>(SketchMapper.java:59)
    at SketchMapperTest.setup(SketchMapperTest.java:45)
    at processing.core.PApplet.handleDraw(PApplet.java:2373)
    at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:761)
    at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:691)
    at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:673)
    at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:442)
    at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1277)
    at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1131)
    at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:680)
    at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:77)
    at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:451)
    at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
    at java.util.TimerThread.mainLoop(Timer.java:555)
    at java.util.TimerThread.run(Timer.java:505)
```

I'm sure there's some notes in the processing repo for how to get the sketch path in version 3. Just need to find em.

**Comment by josephtaylor** [comment]
fix in for this in processing3 branch
